name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Show Swift version
        run: swift --version
      - name: Build
        run: |
          xcodebuild clean build \
            -sdk iphonesimulator \
            -workspace SwipeMenuViewController.xcworkspace \
            -scheme SwipeMenuViewController \
            CODE_SIGNING_REQUIRED=NO
